server:
    port: ${PORT:${SERVER_PORT:8082}}
    
spring:
    data:
        mongodb:
            authentication-database: admin
            host: mongodb
            port: 27017
            username: mongoadmin
            password: secret
            database: mydatabase
        rabbitmq:
            addresses: rabbitmq:5672
    zipkin:
        base-url: http://zipkin-service:9411
    kafka:
        streams:
            bootstrap-servers: kafka-service:29092
        consumer:
            group-id: microservicesdemo
            template:
                default-topic: topic1
    rabbitmq:
        addresses: rabbitmq-service:5672
    
eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://eurekaserver-service:8761/eureka
        enabled: true
           
rabbitmq:
    exchanges:
        direct: direct.exchange
        dead: dead.exchange
    queues:
        file: file.queue
        dead: dead.queue
    routing-keys:
        file: file.routing-key
        dead: dead.routing-key