spring:
  application:
    name: gateway-server  
  zipkin:
        base-url: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/**
            
        - id: university-service
          uri: lb://university-service
          predicates:
            - Path=/university-service/**
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
    

server:
    port: 8080
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true